[project]
name = "pludot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "maturin>=1.13.3",
    "polars>=1.41.2",
]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "datasets>=4.8.5",
    "marimo>=0.23.8",
    "pytz>=2026.2",
]
